x-app: &app
    build:
      context: .
      args:
        RUBY_VERSION: '2.7'
    # Increase the version number in the image tag every time Dockerfile or its arguments is changed
    image: ontologies_api:0.0.1
    environment:
      - BUNDLE_PATH=/srv/ontoportal/bundle
      #- COVERAGE=true
      #- OVERRIDE_CONNECT_GOO=true
      - GOO_BACKEND_NAME=4store
      - GOO_PORT=9000
      - GOO_HOST=4store-ut
      - GOO_PATH_QUERY=/sparql/
      - GOO_PATH_DATA=/data/
      - GOO_PATH_UPDATE=/update/
      - REDIS_HOST=redis-ut
      - REDIS_PORT=6379
      - SORL_HOST=solr-ut
      - SOLR_TERM_SEARCH_URL=http://solr-ut:8983/solr/term_search_core1
      - SOLR_PROP_SEARCH_URL=http://solr-ut:8983/solr/prop_search_core1
      - MGREP_HOST=mgrep-ut
      - MGREP_PORT=55555
    volumes:
      # bundle volume for hosting gems installed by bundle; it helps in local development with gem udpates
      - bundle:/srv/ontoportal/bundle
      # api code
      - .:/srv/ontoportal/ontologies_api
    depends_on:
      - solr-ut
      - redis-ut
      - 4store-ut
      - mgrep-ut

services:
  api:
    <<: *app
    stdin_open: true
    tty: true
    command: "bundle exec rackup -o 0.0.0.0 --port 9393"
    ports:
      - "9393:9393"

  redis-ut:
    image: redis

  4store-ut:
    image: bde2020/4store
    #volume: fourstore:/var/lib/4store
    command: >
      bash -c "4s-backend-setup --segments 4 ontoportal_kb
      && 4s-backend ontoportal_kb
      && 4s-httpd -D -s-1 -p 9000 ontoportal_kb"

  solr-ut:
    image: ontoportal/solr-ut:0.1

  mgrep-ut:
    image: ontoportal/mgrep-ncbo:0.1

volumes:
  bundle:
  #fourstore:
