name: Ruby Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker-compose
      run: docker-compose build
    - name: Run unit tests
      run: docker-compose run --rm api-agraph wait-for-it solr-ut:8983 -- bundle exec rake test
