name: Ruby Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        backend: ['api', 'api-agraph'] # api runs tests with 4store backend and api-agraph runs with AllegroGraph backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker-compose
      run: docker-compose build --profile 4store
    - name: Run unit tests
      run: docker-compose run --rm ${{ matrix.backend }} wait-for-it solr-ut:8983 -- bundle exec rake test TESTOPTS='-v'
