name: Ruby Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker-compose
      working-directory: ./test
      run: docker-compose build
    - name: Run unit tests
      working-directory: ./test
      run: docker-compose run --rm unit-test wait-for-it solr-ut:8984 -- bundle exec rake test TESTOPTS='-v'
